apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: mini-llm-serving
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/part-of: mini-llm-serving-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dcgm-exporter
        app.kubernetes.io/part-of: mini-llm-serving-platform
    spec:
      containers:
        - name: dcgm-exporter
          image: nvcr.io/nvidia/k8s/dcgm-exporter:3.3.9-3.6.1-ubuntu22.04
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9400
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: mini-llm-serving
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/part-of: mini-llm-serving-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dcgm-exporter
  ports:
    - name: metrics
      port: 9400
      targetPort: metrics
