apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../k8s
  - vllm-config.yaml
  - vllm-secret.yaml
  - vllm-deployment.yaml
  - vllm-service.yaml
  - dcgm-exporter.yaml
patches:
  - path: gateway-config-patch.yaml
  - path: gateway-secret-patch.yaml
  - path: prometheus-config-patch.yaml
