apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: mini-llm-serving
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: mini-llm-serving-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
