apiVersion: v1
kind: Secret
metadata:
  name: vllm-secret
  namespace: mini-llm-serving
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: mini-llm-serving-platform
type: Opaque
stringData:
  VLLM_API_KEY: local-vllm-key
  HUGGING_FACE_HUB_TOKEN: ""
