apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "mini-llm.componentLabels" (dict "name" "gateway") | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
