apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: mini-llm-serving
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: mini-llm-serving-platform
type: Opaque
stringData:
  API_KEYS: dev-key,team-a-key
