apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: mini-llm-serving
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: mini-llm-serving-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
