apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-secret
  namespace: mini-llm-serving
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production-secret-store
    kind: ClusterSecretStore
  target:
    name: gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEYS
      remoteRef:
        key: mini-llm/gateway
        property: api-keys
    - secretKey: VLLM_API_KEY
      remoteRef:
        key: mini-llm/vllm
        property: api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vllm-secret
  namespace: mini-llm-serving
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production-secret-store
    kind: ClusterSecretStore
  target:
    name: vllm-secret
    creationPolicy: Owner
  data:
    - secretKey: VLLM_API_KEY
      remoteRef:
        key: mini-llm/vllm
        property: api-key
    - secretKey: HUGGING_FACE_HUB_TOKEN
      remoteRef:
        key: mini-llm/huggingface
        property: token
